[package]
name = "blinkin_led"
version = "0.1.0"
authors = ["purcx"]

[dependencies]
cortex-m = "0.1.4"
r0 = "0.1.0"

[dependencies.stm32f7_discovery]
git = "https://github.com/embed-rs/stm32f7-discovery.git"
version = "0.1.0"

[profile.release]
lto = true


